### Drill: Query, Slicing, Combining arrays

- Run the first cell to create two 5x3 integer arrays

In [1]:
import numpy as np

np.random.seed(15)

ar1 = np.random.randint(15, size=(5, 3))
ar2 = np.random.randint(7, size=(5, 3))

In [2]:
# printout of the two arrays made above
print(ar1)
print("-" * 60)
print(ar2)

[[ 8  5 12]
 [ 5  7  0]
 [12 11  7]
 [11  5  6]
 [13  1 13]]
------------------------------------------------------------
[[0 6 2]
 [4 1 5]
 [3 4 5]
 [4 5 6]
 [0 2 1]]


<h3>Slicing NumPy arrays</h3>

We can select a <font color='red'>subset</font> of rows and columns in the [ ]. The left-most operator operates on the rows (just a colon selects all rows). The range after the comma operates on the columns (e.g.[, 1:3] select columns 1 & 2). 
```
ar[:,1:3]
```

From the arrays created above:

- Use [] slicing to print out the last 2 rows of ```ar1```
- Use [] slicing to print out the first column of `ar2`

In [3]:
ar1[-2:,:]

array([[11,  5,  6],
       [13,  1, 13]])

In [4]:
ar2[:,0:1]

array([[0],
       [4],
       [3],
       [4],
       [0]])

- Use [] slicing to print out the row 2 and columns 2 & 3 from `ar1`
- Use [] slicing to print out the last 2 rows and last column of `ar2`

In [5]:
ar1[1:2,1:4]

array([[7, 0]])

In [6]:
ar2[-2:,-1:]

array([[6],
       [1]])

- Use [] slicing to print out the first element of `ar1`
- Use [] slicing to print out the last element of `ar2`

In [7]:
ar1[0,0]

8

In [8]:
ar2[-1,-1]

1

#### Stacking array
- Use vstack and hstack on the two arrays ar1 and ar2
- What's the result?

In [9]:
np.vstack([ar1, ar2])

array([[ 8,  5, 12],
       [ 5,  7,  0],
       [12, 11,  7],
       [11,  5,  6],
       [13,  1, 13],
       [ 0,  6,  2],
       [ 4,  1,  5],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 0,  2,  1]])

In [10]:
np.hstack([ar1, ar2])

array([[ 8,  5, 12,  0,  6,  2],
       [ 5,  7,  0,  4,  1,  5],
       [12, 11,  7,  3,  4,  5],
       [11,  5,  6,  4,  5,  6],
       [13,  1, 13,  0,  2,  1]])

#### Concatenation... 
Using our <code>ar1</code> and <code>ar2</code>, let&rsquo;s concatenate them, experimenting on the axis (1 or 0).   First, let's try on axis = 1.  What do you see?  Next try axis = 0 and compare.

&#x1f601; Pretty cool, no? &#x1f638;
- Whats the difference between concatenate aand v/hstack?

In [11]:
np.concatenate((ar1, ar2), axis=1)

array([[ 8,  5, 12,  0,  6,  2],
       [ 5,  7,  0,  4,  1,  5],
       [12, 11,  7,  3,  4,  5],
       [11,  5,  6,  4,  5,  6],
       [13,  1, 13,  0,  2,  1]])

In [12]:
np.concatenate((ar1, ar2), axis=0)

array([[ 8,  5, 12],
       [ 5,  7,  0],
       [12, 11,  7],
       [11,  5,  6],
       [13,  1, 13],
       [ 0,  6,  2],
       [ 4,  1,  5],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 0,  2,  1]])

##### Splitting Arrays
To split an array into multiple smaller sub-arrays - use np.split()
- Split array ```ar1``` into 5 arrays 

In [13]:
np.split(ar1, 5)

[array([[ 8,  5, 12]]),
 array([[5, 7, 0]]),
 array([[12, 11,  7]]),
 array([[11,  5,  6]]),
 array([[13,  1, 13]])]